version: '3'
services:
  web:
    environment:
      - MONGO_DB_HOST=mongo
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_SERVICE_NAME=app-notas
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_MANAGER_HOST_PORT=jaeger:5778
    build: .
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: npm run dev

    depends_on:
      - mongo
      - jaeger

    networks:
      - default

    
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - default

  jaeger: 
    image: jaegertracing/all-in-one:latest

    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks:
      - default

  hotrod:
    image: jaegertracing/example-hotrod:latest
    ports: 
      - "8080:8080"
    command: ["all"]
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
    networks:
      - default
    depends_on:
      - jaeger
networks:
  default:
