name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MONGO_DB_HOST: localhost
      MONGO_DB_PORT: 27017

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    steps:
    - name: Wait for MongoDB to start
      run: |
        while ! nc -z localhost 27017; do
          echo "Waiting for MongoDB to start..."
          sleep 1
        done
        echo "MongoDB is available."

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install
      
    - name: Run Unit Tests
      run: npm test
      
    - name: Lint Code with ESLint
      run: npm run lint

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/app-notas .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/app-notas

 




