name: CI

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MONGO_DB_HOST: localhost
      MONGO_DB_PORT: 27017

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    steps:
    - name: Wait for MongoDB to start
      run: |
        while ! nc -z localhost 27017; do
          echo "Waiting for MongoDB to start..."
          sleep 1
        done
        echo "MongoDB is available."

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install
      
    - name: Run Unit Tests
      run: npm test
      
    - name: Lint Code with ESLint
      run: npm run lint

 




